require: rubocop-performance

AllCops:
    TargetRubyVersion: 2.4

# Metrics are too arbitrary.
Metrics/AbcSize:
    Enabled: false
Metrics/ClassLength:
    Enabled: false
Layout/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false

# Weird.
Style/FormatStringToken:
    Enabled: false
Style/NumericPredicate:
    Enabled: false

# Trailing commas are good.
Style/TrailingCommaInArguments:
    Enabled: false
Style/TrailingCommaInArrayLiteral:
    Enabled: false
Style/TrailingCommaInHashLiteral:
    Enabled: false

# Use unless as much as possible? I disagree!
Style/NegatedIf:
    Enabled: false

# This reduces indentation.
Style/ClassAndModuleChildren:
    EnforcedStyle: compact

# This doesn't always make sense.
Style/IfUnlessModifier:
    Enabled: false

# These are new and rubocop warns if you don't configure them.
Style/HashEachMethods:
    Enabled: true
# This should only be enabled when we are on Ruby 2.5+.
Style/HashTransformKeys:
    Enabled: false
Style/HashTransformValues:
    Enabled: true
